---
- name: Reinstall Prometheus Process Exporter
  hosts: computenodes
  become: true
  vars:
    src_dir: "{{ lookup('ansible.builtin.env', 'HOME') }}/prometheus/exporters/process_exporter"
    exe_dir: "process-exporter-0.8.7"

  tasks:
    - name: Copy executable
      ansible.builtin.copy:
        src: "{{ src_dir }}/{{ exe_dir }}/process-exporter"
        dest: /usr/local/bin/process-exporter
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx

    - name: Scan for unit and restart it
      ansible.builtin.systemd:
        name: prometheus-process-exporter.service
        state: restarted
