---
- name: Set up Prometheus Process Exporter
  hosts: computenodes
  become: true
  vars:
    src_dir: "{{ lookup('ansible.builtin.env', 'HOME') }}/prometheus/exporters/process_exporter"
    cfg_dir: "config"

  tasks:
    - name: Copy config file
      ansible.builtin.copy:
        src: "{{ src_dir }}/{{ cfg_dir }}/process_exporter.yml"
        dest: /usr/local/etc/process_exporter.yml
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: Scan for new unit and restart it
      ansible.builtin.systemd:
        daemon_reload: true
        name: prometheus-process-exporter.service
        state: restarted
