---
- name: Copy SLURM config file to all nodes
  hosts: headnode,computenodes
  become: true
  vars:
    src_dir: "{{ lookup('ansible.builtin.env', 'HOME') }}/slurm/configs"

  tasks:
    - name: Copy slurm.conf
      ansible.builtin.copy:
        src: '{{ src_dir }}/slurm.conf'
        dest: /etc/slurm-llnl/slurm.conf
        owner: root
        group: root
        mode: '0644'
